// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using net_pers_fin.Data;

#nullable disable

namespace net_pers_fin.Migrations
{
    [DbContext(typeof(net_pers_fin_context))]
    [Migration("20240812024040_updatedUserCreatedonField")]
    partial class updatedUserCreatedonField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("net_pers_fin.Models.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("first")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("last")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastlogin")
                        .HasColumnType("TEXT");

                    b.Property<int>("verified")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
